name = "SkyDomes"
uuid = "1838625c-7cf7-40c6-898b-904883e4b556"
authors = ["Alejandro Morales Sierra <morales.s.alejandro@gmail.com> and contributors"]
version = "0.1.1"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
PlantGeomPrimitives = "7eef3cc5-4580-4ff0-8f6f-933507db6664"
PlantRayTracer = "78485975-e4aa-407d-b3bb-ded5a4265d05"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
DataFrames = "1.6.1"
HCubature = "1.5.1"
PlantGeomPrimitives = "0.0.2"
PlantRayTracer = "0.0.2, 0.0.3"
StaticArrays = "1.6.2"
julia = "1.9"
